name: Compile Schedule

on:
  workflow_dispatch:

jobs:
  compile_schedule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex texlive-fonts-extra texlive-luatex tex-gyre
        python -m pip install pandas

    - name: Compile Schedule
      env:
        TEXINPUTS: .//latex//
      run: python compile_schedule.py

    - name: Upload Schedule PDF
      uses: actions/upload-artifact@v2
      with:
        name: events_schedule
        path: events_schedule.pdf
