name: Launch Events

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  generate_event_reminders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install pandas
        python -m pip install pyyaml

    - name: Generate event reminder scripts
      run: python generate_event_reminders.py
      env:
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}

    - name: Configure git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit new workflows
      run: |
        git add .github/workflows/reminder_*.yml
        git commit -m "Add event reminder workflows"

    - name: Push changes
      uses: github-actions-x/push-to-another-repository@v1.7.0
      with:
        source-directory: "."
        destination-github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        destination-repository: ${{ github.repository }}
        user-email: 'github-actions[bot]@users.noreply.github.com'
        user-name: 'github-actions[bot]'
        commit-message: "Add event reminder workflows"
