jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Send email
      run: |
        python - <<EOF
        import smtplib
        from email.mime.multipart import MIMEMultipart
        from email.mime.text import MIMEText

        sender_email = "jeremy.manning@gmail.com"
        receiver_email = "jeremy.manning+admin@gmail.com"
        cc_email = "jeremy@dartmouth.edu, jeremy.r.manning@dartmouth.edu"
        subject = "Game Night Reminder"

        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = receiver_email
        msg['Cc'] = cc_email
        msg['Subject'] = subject

        body = """Hi Michelle,

        Could you please send out the announcement below to the department?

        Thanks very much!

        Best,
        The PBS Social Committee

        ===BEGIN===
        PBS Social Committee Calendar of Events

        Game Night 🎲

        Join us for a fun Game Night! Bring your favorite games and enjoy an evening of laughter and friendly competition.

        **Date:** Wednesday, November 6
        **Time:** TBD
        **Location:** TBD

        Looking forward to a fun night!

        Best,
        The PBS Social Committee
        ===END===
        """
        msg.attach(MIMEText(body, 'plain'))

        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, "${{ secrets.GMAIL_PASSWORD }}")
        text = msg.as_string()
        server.sendmail(sender_email, receiver_email.split(", ") + cc_email.split(", "), text)
        server.quit()
        EOF
name: Reminder for Game Night
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 5 11 *"
