name: Reminder for Winter Holiday Party
'on':
  workflow_dispatch: {}
  schedule:
  - cron: 0 9 14 12 *
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install markdown
    - name: Send email
      run: "python - <<EOF\n\nimport smtplib\nfrom email.mime.multipart import MIMEMultipart\n\
        from email.mime.text import MIMEText\n\nsender_email = \"jeremy.manning@gmail.com\"\
        \nreceiver_email = \"jeremy.manning+admin@gmail.com\"\ncc_email = \"jeremy@dartmouth.edu,\
        \ jeremy.r.manning@dartmouth.edu\"\nsubject = \"Winter Holiday Party Reminder\"\
        \n\nmsg = MIMEMultipart()\nmsg['From'] = sender_email\nmsg['To'] = receiver_email\n\
        msg['Cc'] = cc_email\nmsg['Subject'] = subject\n\nbody = \"\"\"<p>Hi Michelle,</p>\n\
        <p>Could you please send out the announcement below to the department?</p>\n\
        <p>Thanks very much!</p>\n<p>Best,\nThe PBS Social Committee</p>\n<p>===BEGIN===\n\
        PBS Social Committee Calendar of Events</p>\n<p>Winter Holiday Party \U0001F389\
        \u2744\uFE0F\u26C4\U0001F939</p>\n<p>Join us for our Winter Holiday Party!\
        \ Celebrate the season with colleagues, friends, and family.</p>\n<p><strong>Date:</strong>\
        \ Mid-December\n<strong>Time:</strong> TBD\n<strong>Location:</strong> TBD</p>\n\
        <p>Let's spread some holiday cheer!</p>\n<p>Best,\nThe PBS Social Committee</p>\n\
        <p>===END===</p>\"\"\"\nmsg.attach(MIMEText(body, 'html'))\n\nserver = smtplib.SMTP('smtp.gmail.com',\
        \ 587)\nserver.starttls()\nserver.login(sender_email, \"${ secrets.GMAIL_PASSWORD\
        \ }\")\ntext = msg.as_string()\nserver.sendmail(sender_email, receiver_email.split(',\
        \ ') + cc_email.split(', '), text)\nserver.quit()\n\nEOF"
