name: Reminder for Hikes with The Chair
'on':
  workflow_dispatch: {}
  schedule:
  - cron: 0 9 27 9 *
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install pandas markdown
    - name: Run email script
      run: python scripts/send_email_Hikes_with_The_Chair.py
      env:
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
