name: Reminder for Weekly Bagel Brunch
'on':
  workflow_dispatch: {}
  schedule:
  - cron: 0 9 26 9 *
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install markdown
    - name: Run email script
      run: python scripts/send_email_Weekly_Bagel_Brunch.py
