jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install smtplib email
    - name: Send email
      run: "python - <<EOF\nimport smtplib\nfrom email.mime.multipart import MIMEMultipart\n\
        from email.mime.text import MIMEText\n\nsender_email = \"jeremy.manning@gmail.com\"\
        \nreceiver_email = \"jeremy.manning+admin@gmail.com\"\ncc_email = \"jeremy@dartmouth.edu,\
        \ jeremy.r.manning@dartmouth.edu\"\nsubject = \"Weekly Bagel Brunch Reminder\"\
        \n\nmsg = MIMEMultipart()\nmsg['From'] = sender_email\nmsg['To'] = receiver_email\n\
        msg['Cc'] = cc_email\nmsg['Subject'] = subject\n\nbody = \"\"\"Hi Michelle,\n\
        \nCould you please send out the announcement below to the department?\n\n\
        Thanks very much!\n\nBest,\nThe PBS Social Committee\n\n===BEGIN===\nPBS Social\
        \ Committee Calendar of Events\n\nWeekly Bagel Brunch \U0001F96F\u2615\uFE0F\
        \U0001F375\n\nHelp yourself to a variety of bagels, cream cheese, and conversations\
        \ with colleagues. Please bring your own coffee, tea, and conversation.\n\n\
        **Date:** Fridays throughout the term\n**Time:** 10:00 \u2013 11:00 AM\n**Location:**\
        \ Bucci Lounge, Moore Hall, 2nd floor\n\nSee you there!\n\nBest,\nThe PBS\
        \ Social Committee\n\n\n===END===\n\"\"\"\nmsg.attach(MIMEText(body, 'plain'))\n\
        \nserver = smtplib.SMTP('smtp.gmail.com', 587)\nserver.starttls()\nserver.login(sender_email,\
        \ \"eswl nrrh khqw aoex\")\ntext = msg.as_string()\nserver.sendmail(sender_email,\
        \ receiver_email.split(\", \") + cc_email.split(\", \"), text)\nserver.quit()\n\
        \nEOF"
name: Reminder for Weekly Bagel Brunch
'on':
  schedule:
  - cron: '2024-09-26T14:00:00Z'
