jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install smtplib email
    - name: Send email
      run: "python - <<EOF\nimport smtplib\nfrom email.mime.multipart import MIMEMultipart\n\
        from email.mime.text import MIMEText\n\nsender_email = \"jeremy.manning@gmail.com\"\
        \nreceiver_email = \"jeremy.manning+admin@gmail.com\"\ncc_email = \"jeremy@dartmouth.edu,\
        \ jeremy.r.manning@dartmouth.edu\"\nsubject = \"Game Night Reminder\"\n\n\
        msg = MIMEMultipart()\nmsg['From'] = sender_email\nmsg['To'] = receiver_email\n\
        msg['Cc'] = cc_email\nmsg['Subject'] = subject\n\nbody = \"\"\"Hi Michelle,\n\
        \nCould you please send out the announcement below to the department?\n\n\
        Thanks very much!\n\nBest,\nThe PBS Social Committee\n\n===BEGIN===\nPBS Social\
        \ Committee Calendar of Events\n\nGame Night \U0001F3B2\n\nJoin us for a fun\
        \ Game Night! Bring your favorite games and enjoy an evening of laughter and\
        \ friendly competition.\n\n**Date:** Wednesday, November 6\n**Time:** TBD\n\
        **Location:** TBD\n\nLooking forward to a fun night!\n\nBest,\nThe PBS Social\
        \ Committee\n\n\n===END===\n\"\"\"\nmsg.attach(MIMEText(body, 'plain'))\n\n\
        server = smtplib.SMTP('smtp.gmail.com', 587)\nserver.starttls()\nserver.login(sender_email,\
        \ \"${{ secrets.GMAIL_PASSWORD }}\")\ntext = msg.as_string()\nserver.sendmail(sender_email,\
        \ receiver_email.split(\", \") + cc_email.split(\", \"), text)\nserver.quit()\n\
        \nEOF"
name: Reminder for Game Night
'on':
  schedule:
  - cron: 0 0 5 11 *
  workflow_dispatch: {}
